config/routes.rb
Rails.application.routes.draw do
     mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "articles#index"
   
   resources :articles do
     resources :comments, only: [:create, :destroy]
     resource :like, only: [:create, :destroy]
  end
  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
   resource :profile, only: [:show, :edit, :update]
   
   get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :title, presence: true
  validates :content, presence: true

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end
  
  def has_liked?(user)
    likes.exists?(user_id: user.id)
  end
  
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  enum gender: { male: 0, female: 1, other: 2 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  after_create :send_email

  private
  def send_email
    RelationshipMailer.new_follower(following, follower).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy
  
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following
  
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower
  
  
  
  
  delegate :birthday, :gender, to: :profile, allow_nil: true
  
  def has_written?(article)
    articles.exists?(id: article.id)
  end
  
  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def birthday
    profile&.birthday
  end

  def gender
    profile&.gender
  end
  
  
  def follow!(user)
    user_id = get_user_id(user)
    
    following_relationships.create!(following_id: user_id)
  end
  
  def unfollow!(user)
    user_id = get_user_id(user)
    
    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end
  
  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end
  
  
   private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to profile_path
    end
  
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @articles =Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
  end
  
  def create
     @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Successfully　created'
    else
      render :new
    end
  end

  def edit
     @article = current_user.articles.find(params[:id])
  end
  
  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: 'Successfully　updated'
    else
      render :edit
    end
  end
  
  def destroy
     article = current_user.articles.find(params[:id])
     article.destroy!
     redirect_to articles_path, notice: 'Successfully　deleted'
  end
  
  
  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params) 
    @comment.user_id = current_user.id 
    if @comment.save
      render :index #④
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index #⑥
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    current_user.follow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    like = current_user.likes.new(article_id: @article.id)
    like.save
    
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    like = current_user.likes.find_by!(article_id: @article.id)
    like.destroy!
    
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.build_profile
  end
  
  def update
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィール更新！'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed
    )
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/unfollows_helper.rb
module UnfollowsHelper
end

app/views/articles/_article.html.erb
<%= link_to article_path(article) do %>
  <div class="card">
    <div class="card_image">
      <%= image_tag 'no_image.jpeg' %>
    </div>
    <div class="card_content">
      <div class="card_title">
        <%= article.title %>
      </div>
      <div class="card_heart">
        <%= image_tag 'heart.svg' %>
        <span><%= article.likes.count %></span>
      </div>
      <div class="card_detail">
        <%= image_tag 'no_image.jpeg' %>
        <div>
          <p><%= article.user.name %></p>
          <p><%= article.display_created_at %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
  <ul>
    <% article.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%= form_with(model: article, url: articles_path, method: 'post', local: true) do |f| %>
    <div>
      <%= f.label :title, 'タイトル' %>
    </div>
    <div>
      <%= f.text_field :title, class: 'text' %>
    </div>
    <div>
      <%= f.label :content, '内容' %>
    </div>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit '保存', class: 'btn-primary' %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="container">
  
   
  <% @articles.each do |article| %>
   <%= render 'article', article: article %> 
  <% end %>
  
  <%= link_to new_article_path do %>
    <div class="float_btn">
      <i class="fa fa-plus"></i>
    </div>
  <% end %>
</div>


    
  

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="article">
  <h1 class="article_title"><%= @article.title %></h1>
  <div class="article_detail">
    <%= link_to account_path(@article.user) do %>
      <%= image_tag 'no_image.jpeg' %>
    <% end %>
    <div>
      <p><%= @article.user.name %></p>
      <p><%= @article.display_created_at %></p>
    </div>
    <% if user_signed_in? && current_user.has_written?(@article) %>
      <div class="article_detail_actions">
        <div class="dropdown">
          <%= image_tag 'actions.svg', class: 'dropbtn' %>
            <div class="dropdown-content mini">
              <%= link_to '編集する', edit_article_path(@article) %>
              <%= link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' } %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="article_content">
    <%= @article.content %>
  </div>
  <div id="show_like_<%= @article.id %>">
   <%= render 'likes/like', article: @article %>
  </div>
</div>
<div class="container">
  <div>
    <p>コメント件数：<%= @comments.count %></p>

    <div id="comments_area">
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
     <%= render 'comments/index', comments: @comments %>
    </div>
  </div>
  <div>
    <% if user_signed_in? %>
      <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
      <%= render 'comments/form', {article: @article , comment: @comment} %>
    <% end %>
  </div>

  <%= link_to "Topへ戻る", articles_path %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [article, comment], local: false do |f| %>
  <%= f.text_area :content, rows: '5', placeholder: "コメントをここに" ,class: "comment_area"%>
  <%= f.submit "送信する", class: "btn-primary" %>
 <% end %>

app/views/comments/_index.html.erb
 <% comments.each do |comment| %>
  <p><%= image_tag "no_image.jpeg" %></p>
  <%= comment.user.name %>
  <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.content %>
  <% if comment.user == current_user %>
    <%= link_to "削除", article_comment_path(comment.article, comment), method: :delete, remote: true, data: {confirm: "本当に削除しますか？"} %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.article.comments }) %>")
$("textarea").val('')

app/views/likes/_like.html.erb
 <% if user_signed_in? %>
  <% if article.has_liked?(current_user)%>
    <div class="article_heart">
      <%= link_to article_like_path(article), data: { method: 'delete' },remote: true  do %>
        <%= image_tag 'heart-active.svg'%>
      <% end %>
    </div>
  <% else %>
    <div class="article_heart">
      <%= link_to article_like_path(article), data: { method: 'post' },remote: true  do %>
        <%= image_tag 'heart.svg'%>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/likes/create.js.erb
//投稿詳細いいね差し替え
$("#show_like_<%= @article.id %>").html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");

app/views/likes/destroy.js.erb
//投稿詳細いいね差し替え
$("#show_like_<%= @article.id %>").html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");

app/views/profiles/edit.html.erb
<div class="container">
  <ul>
    <% @profile.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%= form_with(model: @profile, url: articles_path, method: 'post', local: true) do |f| %>
    <div>
      <%= f.label :nickname, 'ハンドルネーム' %>
    </div>
    <div>
      <%= f.text_field :nickname, class: 'text' %>
    </div>
    <div>
      <%= f.label :introduction, '自己紹介' %>
    </div>
    <div>
      <%= f.text_area :introduction %>
    </div>
    <div>
      <%= f.label :gender, '性別' %>
    </div>
    <div>
      <%= f.select :gender, Profile.genders.keys, {}, { class: 'text' } %>
    </div>
    <div>
      <%=f.label :birthday, '生年月日' %>
    </div>
    <div>
      <%=f.date_field :birthday, class: 'text' %>
    </div>
    <div>
      <%=f.label :subscribed, '通知を受け取る'%>
      <%=f.check_box :subscribed %>
    </div>
    
    
    <%= f.submit '保存', class: 'btn-primary' %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<%= render 'commons/profile', user: current_user %>