config/routes.rb
Rails.application.routes.draw do
     mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "articles#index"
   
   resources :articles do
     resources :comments, only: [:create, :destroy]
     resource :like, only: [:create, :destroy]
  end
  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
   resource :profile, only: [:show, :edit, :update]
   
   get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :title, presence: true
  validates :content, presence: true

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end
  
  def has_liked?(user)
    likes.exists?(user_id: user.id)
  end
  
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  enum gender: { male: 0, female: 1, other: 2 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  after_create :send_email

  private
  def send_email
    RelationshipMailer.new_follower(following, follower).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy
  
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following
  
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower
  
  
  
  
  delegate :birthday, :gender, to: :profile, allow_nil: true
  
  def has_written?(article)
    articles.exists?(id: article.id)
  end
  
  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def birthday
    profile&.birthday
  end

  def gender
    profile&.gender
  end
  
  
  def follow!(user)
    user_id = get_user_id(user)
    
    following_relationships.create!(following_id: user_id)
  end
  
  def unfollow!(user)
    user_id = get_user_id(user)
    
    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end
  
  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end
  
  
   private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to profile_path
    end
  
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    current_user.follow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    like = current_user.likes.new(article_id: @article.id)
    like.save
    
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    like = current_user.likes.find_by!(article_id: @article.id)
    like.destroy!
    
    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/unfollows_helper.rb
module UnfollowsHelper
end

app/views/commons/_profile.html.erb
<div class="container profilePage">
  <div class="profilePage_user">
    <div class="profilePage_user_image">
      <%= image_tag 'no_image.jpeg' %>
    </div>
    <div class="profilePage_user_basicInfo">
      <div class="profilePage_user_name">
        <div class="profilePage_user_displayName">
          <%= user.name %>
        </div>
        <div class="profilePage_user_actionButton">
          <% if user == current_user %>
            <%= link_to 'Edit', edit_profile_path %>
          <% else %>
            <% if current_user&.has_followed?(user) %>
              <%= link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'} %>
            <% else %>
              <%= link_to 'Follow', account_follows_path(user), data: {method: 'post'} %>
            <% end %>
          <% end %>
          
        </div>
      </div>
      <div class="profilePage_user_introduction">
        <%= user.profile&.introduction%>
      </div>
    </div>
  </div>

  <% user.articles.each do |article| %>
    <%= render 'articles/article', article: article %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Akolog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="header_pageTitle">
        <%= link_to 'Akolog', root_path %></div>
      <div class="dropdown">
        <%= image_tag 'no_image.jpeg', class: 'header_avatar dropbtn' %>
        <div class="dropdown-content">
          <% if user_signed_in? %>
            <%= link_to 'プロフィール', profile_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }%>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path,class: "nav-link text-light" %> 
            <%= link_to "Log In" ,new_user_session_path,class: "nav-link text-light" %> 
          <% end %>
        </div>
      </div>
    </header>
    <p class="notice"><%= notice %>
    <p class="alert"><%= alert %>
    <%= yield %>
  </body>
</html>